#
# Makefile iio/switches
#

# When adding new entries keep the list in alphabetical order
obj-$(CONFIG_MASW010350) += masw_010350.o
obj-$(CONFIG_RX1) += rx1.o
obj-$(CONFIG_RX2) += rx2.o
obj-$(CONFIG_I2C_CPLD_BRIDGE) += i2c-cpld-bridge.o
obj-$(CONFIG_RX1_DEMOD) += rx1_demod.o
obj-$(CONFIG_TRIGGER_SYNC) += trigger_sync.o
