#
# Makefile for industrial I/O potentiometer drivers
#

# When adding new entries keep the list in alphabetical order
obj-$(CONFIG_MCP4531) += mcp4531.o
obj-$(CONFIG_TPL0102) += tpl0102.o
obj-$(CONFIG_TQP4M9072) += tqp4m9072.o
